//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLVIII_Bojana_Buljic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrderItem
    {
        public int ID { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int Quantity { get; set; }
        public int OrderID { get; set; }
        public string PizzaName { get; set; }
        public int Price { get; set; }
        public int TotalPrice { get; set; }
        public string JMBG { get; set; }
    }
}
